###########################################################################
# ALTHOR : Maxswell Diniz												   #
# Profissional : Técnico em informática									   #
# Data: 06/05/2023														   #
#																		   #
# Projeto: DBA InnoBayte informática									   #
# Sistema de Cadastro de Cliente e Ordem de Serviço de Assistência Técnica #
# Versão 1.0															   #
#																		   #
###########################################################################

-- CRIANDO O BANCO DE DADOS

CREATE DATABASE INNOBAYTE;
USE INNOBAYTE;

/* 01 - INSERINDO A TABELA CLIENTE */

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,

	NOME_COMPLETO VARCHAR(100) NOT NULL,
	CPF VARCHAR(20) UNIQUE,
	EMAIL VARCHAR(50) UNIQUE,
	-- INSERINDO ABAIXO A DATA DE CADASTRO DE FORMA AUTOMÁTICA
	DATA_CADASTRO DATETIME DEFAULT CURRENT_TIMESTAMP

);

# CRIANDO COLUNA SEXO
ALTER TABLE CLIENTE
ADD SEXO ENUM('F','M') NOT NULL;

# COLOCANDO A COLUNA SEXO ENTRE O NOME COMPLETO E O CPF
ALTER TABLE CLIENTE
MODIFY COLUMN SEXO ENUM('F','M') NOT NULL AFTER NOME_COMPLETO ;


-- 01 INSERINDO O PRIMEIRO CADASTRO DO CLIENTE PARA TESTE.

INSERT INTO CLIENTE (NOME_COMPLETO,CPF,EMAIL) VALUES('Maxswell Sousa Diniz','15069366793','maxswellsousadiniz@yahoo.com');
INSERT INTO CLIENTE (NOME_COMPLETO,CPF,EMAIL) VALUES('Diniz Sousa ','917382465','maxswellsousadiniz@yahoo.com');
INSERT INTO CLIENTE (NOME_COMPLETO,CPF,EMAIL) VALUES('Marta Fernandez ','13219673458','Marta@email');

-- 01 INSERINDO O UPDATE DE CADASTRO DO CLIENTE PARA TESTE.

UPDATE CLIENTE SET EMAIL ='max@email.com'
WHERE IDCLIENTE =1;

-- DEPOIS DE ACRESCENTAR A COLUNA SEXO, TODOS OS REGISTRO FICOU COM SEXO FEMININO,NESSE CASO VAMOS APLICAR O UPDATE USANDO INTERVALOS CONFORME O ID
+-----------+----------------------+------+-------------+------------------------------+---------------------+
|         1 | Maxswell Sousa Diniz | F    | 15069366793 | max@email.com                | 2023-05-06 14:40:59 |
|         3 | Diniz Sousa          | F    | 917382465   | maxswellsousadiniz@yahoo.com | 2023-05-06 14:52:10 |
|         5 | Marta Fernandez      | F    | 13219673458 | Marta@email                  | 2023-05-08 09:56:56 |
|         6 | Paulo Brito          | F    | 1762548565  | paulo@email                  | 2023-05-08 10:00:55 |
+-----------+----------------------+------+-------------+------------------------------+---------------------+
-- COLOCANDO O INTERVALO IN PARA APLICAR A MODIFICAÇÃO USANDO INTERVALO DAS CHAVES PRIMÁRIA
UPDATE CLIENTE
SET SEXO = 'M'
WHERE IDCLIENTE IN (1,3,6);
 SELECT * FROM CLIENTE WHERE SEXO = 'M';

-- 01 REALIZANDO TESTE DE DELETE DE DADOS DO CLIENTE
SELECT * FROM CLIENTE WHERE IDCLIENTE =6;

DELETE FROM CLIENTE
WHERE CPF = '13219673458' AND IDCLIENTE =6;

-- 01 REALIZANDO OS SELECT PERSONALIZADO.
SELECT NOME_COMPLETO AS 'NOME', CPF FROM CLIENTE WHERE NOME_COMPLETO like '%Diniz';





#////////////////////////////////////////////////////////////           //////////////////////////////////////////////  //////////////////////////////////////////

/* 02 - CRIANDO A TABELA ENDEREÇO*/

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,

	RUA VARCHAR (100) NOT NULL,
	BAIRRO VARCHAR (50) NOT NULL,
	CIDADE VARCHAR (50) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	ID_CLIENTE INT,

	FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE (IDCLIENTE)

	);


-- 02 REALIZANDO O INSERT DE TESTE DO ENDEREÇO


INSERT INTO ENDERECO VALUES (NULL,'Avenida Central','Centro','Rio de Janeiro','RJ',6);
INSERT INTO ENDERECO VALUES (NULL,'Rua das Flores 123', 'Jardim Primavera', 'São Paulo', 'SP',3);
INSERT INTO ENDERECO VALUES (NULL,'Rua do Comércio 789', 'Centro', 'Belo Horizonte', 'MG',5);
INSERT INTO ENDERECO VALUES (NULL,'Rua das Palmeiras 234', 'Jardim das Oliveiras', 'Brasília', 'DF',1);







#////////////////////////////////////////////////////////////           //////////////////////////////////////////////  //////////////////////////////////////////

/* 03 - REALIZANDO A TABELA DE TELEFONE*/

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('RESIDENCIAL', 'COMERCIAL','CELULAR') NOT NULL,
	NUMERO VARCHAR(20) NOT NULL,
	ID_CLIENTE INT,

	FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE (IDCLIENTE)

);

# NESSA TABELA O CLIENTE PODE TER VÁRIOS NÚMEROS SE DESEJAR E É OBRIGATÓRIO TER UM NÚMERO PARA CONTATO.

INSERT INTO TELEFONE VALUES (NULL,'RESIDENCIAL','64287945',3);
INSERT INTO TELEFONE VALUES (NULL,'RESIDENCIAL','1346852',6);
INSERT INTO TELEFONE VALUES (NULL,'COMERCIAL','1964982',1);
INSERT INTO TELEFONE VALUES (NULL,'CELULAR','39649185',5);



/* PRÓXIMA TAREFA REALIZAR A LIGAÇÃO DAS TABELAS COM CHAVE ESTRANGEIRA E A PROJEÇÃO INNER JOIN*/
CREATE VIEW V_DADOS AS
SELECT NOME_COMPLETO AS "NOME", SEXO,RUA,BAIRRO,TIPO,NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE;


SELECT * FROM V_DADOS;

DROP VIEW V_DADOS;
